/**
* Title: Tokens.h - Project 1
* Description: Tokens used for flex scanner
*/

enum Tokens {RELOP = 256, ADDOP, MULOP, ANDOP, BEGIN_, BOOLEAN, END, ENDREDUCE,
	FUNCTION, INTEGER, IS, REDUCE, RETURNS, IDENTIFIER, INT_LITERAL, ARROW, 
	CASE, ELSE, ENDCASE, ENDIF, IF, OTHERS, REAL, THEN, WHEN, OROP, NOTOP, REMOP, 
	EXPOP, REAL_LITERAL, BOOL_LITERAL};
